Enable loading params from multiple yaml files
ros-controls/gazebo_ros2_control pull request #149
Opened 2022-08-11 10:58 UTC by tonynajjar

2022-08-16 08:05 UTC, tonynajjar commented on gazebo_ros2_control/src/gazebo_system.cpp
> +          mimic_joint.multiplier);
change done by ament_uncrustify

2022-08-17 21:35 UTC, destogl approved these changes

2022-08-18 07:15 UTC, ahcorde requested changes
can you fix linters? https://github.com/ros-controls/gazebo_ros2_control/runs/7853313449?check_suite_focus=true

2022-08-18 09:00 UTC, ahcorde approved these changes

2022-08-18 09:00 UTC, merged

2022-11-16 10:51 UTC, bmagyar commented
do we also need to port this to `gz_ros2_control`?