Mimic joint should have the same control mode as mimicked joint.
ros-controls/gazebo_ros2_control pull request #154
Opened 2022-10-16 18:03 UTC by destogl

With this change gripper example works again.

2022-10-18 09:59 UTC, ahcorde requested changes
linters

2022-11-16 19:19 UTC, christophfroehlich commented
I also ran over this bug accidentally; but this PR works fine. And these small changes make the linter happy:
https://github.com/StoglRobotics-forks/gazebo_ros2_control/pull/1

2022-11-16 19:41 UTC, ahcorde requested changes

2022-11-16 19:41 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_system.cpp
> +  {
```suggestion
  for (const auto & mimic_joint : this->dataPtr->mimic_joints_) {
```

2022-11-16 19:46 UTC, ahcorde approved these changes

2022-11-16 19:46 UTC, merged