Galactic to main
ros-controls/gazebo_ros2_control pull request #165
Opened 2022-11-21 14:18 UTC by ahcorde

2023-01-05 19:39 UTC, destogl requested changes
A few minor comments.

2023-01-05 19:39 UTC, destogl commented on README.md
> +	<limit effort="1000.0" lower="0" upper="0.38" velocity="10"/>
```suggestion
  <mimic joint="right_finger_joint"/>
  <axis xyz="0 1 0"/>
  <origin xyz="0.0 0.48 1" rpy="0.0 0.0 3.1415926535"/>
  <parent link="base"/>
  <child link="finger_left"/>
  <limit effort="1000.0" lower="0" upper="0.38" velocity="10"/>
</joint>

<joint name="right_finger_joint" type="prismatic">
  <axis xyz="0 1 0"/>
  <origin xyz="0.0 -0.48 1" rpy="0.0 0.0 0.0"/>
  <parent link="base"/>
  <child link="finger_right"/>
  <limit effort="1000.0" lower="0" upper="0.38" velocity="10"/>
```

2023-01-05 19:39 UTC, destogl commented on README.md
> +</ros2_control>
```suggestion
<ros2_control name="GazeboSystem" type="system">

  <hardware>
    <plugin>gazebo_ros2_control/GazeboSystem</plugin>
  </hardware>

  <joint name="right_finger_joint">
    <command_interface name="position"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
    <state_interface name="effort"/>
  </joint>

  <joint name="left_finger_joint">
    <param name="mimic">right_finger_joint</param>
    <param name="multiplier">1</param>
    <command_interface name="position"/>
    <state_interface name="position"/>
    <state_interface name="velocity"/>
    <state_interface name="effort"/>
  </joint>

</ros2_control>
```

2023-01-05 19:39 UTC, destogl commented on gazebo_ros2_control/CHANGELOG.rst
> +
Not sure if it is good idea to make changes to CHANGELOG file...

```suggestion
```

2023-01-05 19:39 UTC, destogl commented on gazebo_ros2_control/CHANGELOG.rst
> +=======
```suggestion
```

2023-01-05 19:39 UTC, destogl commented on gazebo_ros2_control_demos/CHANGELOG.rst
> +
```suggestion
```

2023-05-16 13:27 UTC, ahcorde commented
Good question @bmagyar, I will clean the conflicts or close it if this is not relevant

2024-01-23 13:56 UTC, closed without merging