[humble] Force setting use_sim_time parameter when using plugin.
ros-controls/gazebo_ros2_control pull request #175
Opened 2023-01-31 08:31 UTC by Noel215

Cherry-pick https://github.com/ros-controls/gazebo_ros2_control/commit/cc5746bad6820a39d158eec87c0100126f78a6ab from `master` branch to force `use_sim_time` to true in humble

2023-01-31 09:58 UTC, bmagyar approved these changes

2023-02-03 13:32 UTC, ahcorde commented
This PR fixes the CI https://github.com/ros-controls/gazebo_ros2_control/pull/176

2023-02-03 18:01 UTC, ahcorde requested changes
@Noel215 do you mind to merge with `humble` ?

2023-02-06 09:01 UTC, ahcorde approved these changes

2023-02-06 09:01 UTC, merged