Hold joints parameter
ros-controls/gazebo_ros2_control pull request #251
Opened 2023-12-31 12:16 UTC by christophfroehlich

@HPCLOL posted a use case of gazebo in https://github.com/ros-controls/ros2_controllers/issues/875:
If the simulation is started with an inactive controller, the robot should move with gravity as if the joints were passive.

As discussed with #250 this is currently not possible. This PR adds an parameter to enable this behavior (again). 

- I'm not sure if this should be default true or false.
- I haven't found a different solution to tell `GazeboSystem` this parameter parsed from the gazebo plugin without changing API. Therefore, I used a ROS parameter of the gazebo_ros2_control node to pass the information.

2023-12-31 17:43 UTC, saikishor approved these changes
Thanks for the change! LGTM!

After discussion with @christophfroehlich 
We can add a new option for now, as we are limited to one control mode per run of the simulation. Ultimately, I think it will make sense to be able to switch the control modes dynamically once the simulation starts. We can try to aim this for Jazzy. If we can get this switching done, then we can remove this option, as we can achieve the same by switching the control mode to effort.

Ideally, the behavior would be at startup we will have the robot maintaining the position, and then when you switch from position or velocity active controllers to inactive mode, they maintain the old reference, and for the effort based controller, the reference will be set to zero.

What do you think about this new approach for future?

2023-12-31 18:21 UTC, ahcorde requested changes

2023-12-31 18:21 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_system.cpp
> +  } catch (const std::exception & e) {
Include exception

2023-12-31 18:21 UTC, ahcorde commented on gazebo_ros2_control/src/gazebo_ros2_control_plugin.cpp
> +    } catch (const std::exception & e) {
Include exception

2024-01-01 17:21 UTC, christophfroehlich commented
@ahcorde not exactly sure what you requested, I added now explicit catch statements for the exceptions written in the docstring of the rclcpp functions. Or do you have another resource on how to write that properly?

2024-01-01 17:50 UTC, ahcorde commented
> @ahcorde not exactly sure what you requested, I added now explicit catch statements for the exceptions written in the docstring of the rclcpp functions. Or do you have another resource on how to write that properly?

My suggestion was about

```cpp
#include <exception>
```

But this change is also fine

2024-01-01 17:51 UTC, ahcorde approved these changes

2024-01-01 17:52 UTC, merged

2024-01-01 20:46 UTC, christophfroehlich commented
> > @ahcorde not exactly sure what you requested, I added now explicit catch statements for the exceptions written in the docstring of the rclcpp functions. Or do you have another resource on how to write that properly?
> 
> My suggestion was about
> 
> ```c++
> #include <exception>
> ```
> 
> But this change is also fine

Ah :grin: I thought too complicated. Thx!

2024-05-10 17:43 UTC, christophfroehlich commented
@ahcorde Could we backport this please? rolling won't be released any more.

2024-07-06 11:50 UTC, christophfroehlich commented
@mergifyio backport humble iron